#lang planet neil/sicp
(define (make-segment start end)
  (cons start end))
(define (start-segment x)
  (car x))
(define (end-segment x)
  (cdr x))
(define (make-point x y)
  (cons x y))
(define (x-point point)
  (car point))
(define (y-point point)
  (cdr point))
(define (midpoint-segment segment)
 (make-point
   (/ (+ (x-point (end-segment segment))
         (x-point (start-segment segment)))
      2)
   (/ (+ (y-point (end-segment segment))
         (y-point (start-segment segment)))
      2)))
  
(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))

(define start (make-point 1 3))
(define end (make-point 4 3))
(define seg (make-segment start end))
(define mid (midpoint-segment seg))
(print-point mid)
